import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header/Header";
import style from "./RootLayout.module.scss";
import {clsx} from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, style.rootLayout)}>
      <Header/>
      <main className={style.main}>
          <div className={style.inner}>
              {children}
          </div>

      </main>

      </body>
    </html>
  );
}
